pages:
  image: python:latest
  stage: deploy
  script:
    - pip install -r requirements.txt
    - jupyter-book build ./
    - python replace_elements.py
    - mv _build/html public
  artifacts:
    paths:
      - public
  only:
    - master
