# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title                     : "Leerlijn Research Data Management"
author                    : Rick de Klerk
copyright                 : "2021, CC BY 4.0"
logo                      : figures/logo.svg
exclude_patterns          : [_build]
only_build_toc_files      : true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks       : off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url                     : https://github.com/rickdkk/RDM-module-5/  # Online location of your book
  branch                  : main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button       : true
  use_edit_page_button    : true
  use_repository_button   : true
  favicon                 : figures/icon_small.svg  # A path to a favicon image
  extra_navbar            : <a href="https://fontysconnect.nl/rdm">Research Data Management</a>  # Will be displayed underneath the left navbar.
  home_page_in_navbar     : false  # Whether to include your home page in the left Navigation Bar

# Advanced sphinx config
sphinx:
  config:
    panels_css_variables :
      "tabs-color-label-active": "rgba(102, 51, 102, 1)"
      "tabs-color-label-inactive": "rgba(102, 51, 102, 0.62)"
      "tabs-color-overline": "rgba(102, 51, 102, 0.45)"
      "tabs-color-underline": "rgba(102, 51, 102, 0.45)"
      "tabs-size-label": "1rem"
    language: nl
